# Generated by Django 6.0.6 on 2026-06-22 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('avaliable', 'Avaliable'), ('inavaliable', 'Inavaliable')], default='active', max_length=20)),
                ('category', models.CharField(choices=[('rice', 'Rice'), ('beans', 'Beans'), ('soop', 'Soop'), ('swalow', 'Swalow'), ('meat', 'Meat'), ('fish', 'Fish')], default='other', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_poster', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
  